
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract tasksSpis {
    // Contract can have an instance variables.
    // In this example instance variable `timestamp` is used to store the time of `constructor` or `touch`
    // function call
    uint32 public timestamp;
    uint public k=0;
    string[] public list; 
    struct tasks {
        string name;
        uint32 time;
        bool OK;
    }

    // Contract can have a `constructor` – function that will be called when contract will be deployed to the blockchain.
    // In this example constructor adds current time to the instance variable.
    // All contracts need call tvm.accept(); for succeeded deploy
    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        // The current smart contract agrees to buy some gas to finish the
        // current transaction. This actions required to process external
        // messages, which bring no value (henceno gas) with themselves.
        tvm.accept();

        timestamp = now;


        





    }

    function renderHelloWorld () public pure returns (string) {
        return 'helloWorld';
    }

    
     mapping(uint=>tasks) number; 
   
    
    
    

    function addTasks (string name) public returns (uint TaskID) {
        tasks myLes = tasks(name,12,false);
        
        number[TaskID]=myLes;
        list.push(name);
        
        
        return k++;

        
        tvm.accept();
    }

    function changeFlagArraySize(uint newSize) public {
    // if the new size is smaller, removed array elements will be cleared
    list.length = newSize;
    }








    function TasksList ()  public returns (string[] Le) { 
        
        return list[0:1];
         

        
        tvm.accept();
    }

    function trF (tasks[]) public {
            
        }

    

    
}
